### ISSUE TITLE
Setup development environment.

### ISSUE THREAD

**Issue by farookisonfire** [farookkhan/tribal#1]
# Motivation

I want to setup an efficient development environment, that meets project requirements.

# Implementation Details
-  Webpack
-  Babel
-  Express dev server
-  ESLint
-  Jest
-  continuous integration
-  scripts for automated testing and linting

# Task List
- [x] Install dependencies
- [x] Create initial folder structure
- [x] Config Babel for ES6 and React/JSX transpiling
- [x] Config ESLint with recommended settings
- [x] Config Webpack and setup a development server
- [x] Setup Jest and write initial test
- [x] Setup CI with Travis
- [x] Write npm scripts
