### ISSUE TITLE
User can view a list of random users.

### ISSUE THREAD

**Issue by farookisonfire** [farookkhan/tribal#5]
# Motivation
I want the user to be able to see a list of users.

# Implementation Details
- Use the https://randomuser.me/ API to get a list of random users
- Display the list of users using components from Material-UI component library

# Task List
- [x] Make action creators for requesting users.
- [x] Create Reducer to take the action and return new state. 
- [x] Configure Redux store
- [x] Instantiate store and provider
- [x] Create React components 
- [x] Connect the container component to Redux store
- [x] Write unit tests

### Wireframe:
![screen shot 2017-06-10 at 11 53 29 am](https://user-images.githubusercontent.com/19194235/27005431-75c539ae-4dd3-11e7-86b7-035af663273b.png)

**Comment by farookisonfire** [comment]
![screen shot 2017-06-11 at 10 57 28 am](https://user-images.githubusercontent.com/19194235/27013233-cc5bd0b8-4e94-11e7-8d49-7427015dfebe.png)
