### ISSUE TITLE
User can sort users by last name or first name.

### ISSUE THREAD

**Issue by farookisonfire** [farookkhan/tribal#7]
# Motivation
I want the user to be able to sort the list of users by last or first name. By default, the list will be sorted by last name.

# Task List
- [x] Create page divider
- [x] Create sort-by radio buttons
- [x] Add container component local state for sorting
- [x] Create function to sort by a specified value
- [x] Create unit tests
