### ISSUE TITLE
User can search for users.

### ISSUE THREAD

**Issue by farookisonfire** [farookkhan/tribal#9]
# Motivation
I want users to be able to search for other users.

# Implementation Details
The search bar should respond immediately and filter the displayed list of users, showing only the ones whose names contain the search string.

# Task List
- [x] Create search bar component
- [x] Add container component local state containing search string
- [x] Render users if there is a substring match
- [x] Write unit tests
